RESKC-2097: Fix cost sharing issue.There appears to be an issue with Cost Sharing distribution: (#2243)
There appears to be an issue with Cost Sharing distribution:
When a user enters an object code (e.g. personnel) with cost sharing and then navigates to the Cost sharing distribution section, the user gets Javascript errors and gets stuck (the screen's formatting is impacted and the Total Unallocated amount is shown as N/A instead of the actual amount).

Uncaught TypeError: total.replace is not a function